"""added users to company

Revision ID: 5fb101a707bc
Revises: 156cd58adf47
Create Date: 2025-04-01 21:45:34.119957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb101a707bc'
down_revision: Union[str, None] = '156cd58adf47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('user1', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('user2', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('user3', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'companies', ['company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'user3')
    op.drop_column('companies', 'user2')
    op.drop_column('companies', 'user1')
    # ### end Alembic commands ###
